apiVersion: rbac.authorization.k8s.io/v1
kind: Role
# kind: ClusterRole
metadata:
  name: developer
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - "list"
      - "get"
      - "create"
      - "update"
      - "delete"
    # resourceNames:
    #   - "red"
    #   - "blue"
  - apiGroups:
      - ""
    resourceNames:
      - "ConfigMap"
    verbs:
      - "create"