apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
# kind: ClusterRoleBinding
metadata:
  name: devuser-dev-role-binding
subjects:
  - kind: User
    name: devuser
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  # kind: ClusterRole
  name: developer