apiVersion: v1
kind: Config
current-context: admin@my-kube
clusters:
  - name: my-kube
    cluster:
    certificate-authority: /etc/kubernetes/pki/ca.crt
    # certificate-authority-data: <base64-crt-data>
    server: https://my-kube:6443
contexts:
  - name: admin@my-kube
    context:
      cluster: my-kube
      user: admin
      namespace: my-ns
users:
  - name: admin
    user:
      client-certificate: /etc/kubernetes/pki/users/admin.crt
      client-key: /etc/kubernetes/pki/users/admin.key