apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-memory-constraint
  # namespace: default
spec:
  limits:
    - default:
        memory: 1Gi
      defaultRequest:
        memory: 1Gi
      max:
        memory: 1Gi
      min:
        memory: 500Mi
      type: Container