apiVersion: storage.k8s.io/v1
kind: StorageClass # Automatically create PV from cloud provisioners
metadata:
  name: google-storage
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  replication-type: none